## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function
##makeCacheMatrix function used to create a special matrix
##The inverse of this matrix is cached
##In the first step the value of matrix is set
##In the second step the value of matrix is accessed
##In the thirs step the inverse of matrix is set using the solve function
##In the final step the inverse of matrix is accessed
makeCacheMatrix <- function(x = matrix()) {
    i <- NULL
    set <- function(y) {
        x <<- y
        i <<- NULL
    }
    get <- function() x
    setInverse <- function(solve) i <<- matrixInverse
    getInverse <- function() i
    list(set = set, get = get,
         setInverse = setInverse,
         getInverse = getInverse)
}


## Write a short comment describing this function
##cacheSolve function is used to calculate the inverse of the special matrix
##generated by makeCacheMatrix function
##The function first checks if the inverse of the matrix exists
##If the inverse exists, it skips the calculation
##Otherwise computes the inverse using the solve function and sets it value
##using the setInverse function

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
    m <- x$getInverse()
    if(!is.null(i)) {
        message("getting cached data")
        return(i)
    }
    data <- x$get()
    i <- solve(data, ...)
    x$setInverse(i)
    i
}
